/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package counter;

import common.FileUtil;
import common.User;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author johnc
 */
public class CustomerListPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomersList
     */
    public CustomerListPanel() {
        initComponents();
        generateRows();
    }
    
    private void generateRows() {
        FileUtil.loadAllUsers();
        itemsPanel.removeAll();
        itemsPanel.setLayout(new BoxLayout(itemsPanel, BoxLayout.Y_AXIS));

        JPanel header = new JPanel(new GridLayout(1, 5));
        header.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        header.setBorder(new EmptyBorder(5, 5, 5, 5));
        JLabel h1 = new JLabel("Username");
        JLabel h2 = new JLabel("Role");
        JLabel h3 = new JLabel("Phone");
        JLabel h4 = new JLabel("");
        JLabel h5 = new JLabel("Actions");
        h1.setFont(h1.getFont().deriveFont(java.awt.Font.BOLD));
        h2.setFont(h2.getFont().deriveFont(java.awt.Font.BOLD));
        h3.setFont(h3.getFont().deriveFont(java.awt.Font.BOLD));
        h5.setFont(h5.getFont().deriveFont(java.awt.Font.BOLD));
        header.add(h1);
        header.add(h2);
        header.add(h3);
        header.add(h4);
        header.add(h5);
        itemsPanel.add(header);

        for (User u : FileUtil.allUsers) {
            if (u.getRole() == null || !u.getRole().equalsIgnoreCase("Customer")) {
                continue;
            }
            JPanel row = new JPanel(new GridLayout(1, 5));
            row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 35));
            row.setBorder(new EmptyBorder(2, 5, 2, 5));
            row.add(new JLabel(u.getUsername()));
            row.add(new JLabel(u.getRole()));
            row.add(new JLabel(u.getPhoneNumber() != null ? u.getPhoneNumber() : ""));
            row.add(new JButton("Edit"));
            row.add(new JButton("Delete"));
            itemsPanel.add(row);
        }

        itemsPanel.revalidate();
        itemsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemsPanel = new javax.swing.JPanel();

        itemsPanel.setLayout(new javax.swing.BoxLayout(itemsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(itemsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
